### ISSUE TITLE
Gold mine: extraction is too slow 

### ISSUE THREAD

**Issue by SlightPersimmon1** [dalerank/Ozymandias#101]
Gold mine extraction in Ozymadias is too slow. Comparing the original game at 90% speed and Ozymadias at 100% speed (witch are roughly the same - maybe a bug?), the original mining is much faster than on Ozymadias.

**Comment by dalerank** [comment]
thanks, just look inside original game how it slower

**Comment by dalerank** [comment]
![image](https://github.com/dalerank/Ozymandias/assets/918081/32116fbc-adfc-4a1f-866d-7ec06a199708)
add special option for twice goldmine productivity
look inside base code and seems it native speed for Pharaoh
