### ISSUE TITLE
Show full map (now we see only part of it)

### ISSUE THREAD

**Issue by akuskis** [dalerank/Ozymandias#65]
Now part of the map is not reachable, for example this one is not visible:

![image](https://github.com/dalerank/Ozymandias/assets/3109998/1cc1193f-c172-4ac6-9d2a-8a1a9af907de)

This should be done before: #24
Because entry and exit points located on areas which are not reachable by existing view port.

**Comment by dalerank** [comment]
fixed in e409c458d7027a9877b635314c31ed64c1b3894e
